module Gem
	class Author < Struct[untyped]
		VERSION: String

		class Author < Gem::Author
			extend ClassMethods
		end

		module ClassMethods : Class
			@all: Array[self]

			def names:      () -> Array[String]
			def emails:     () -> Array[String]
			def github_url: () -> String?
		end

		def github_url: () -> String?
	end
end
