name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - lib/**
      - spec/**
      - Gemfile*
      - '*.gemspec'
      - .github/workflows/ci.yml
      - .rspec*
      - .rubocop*
      - '!**/version.rb'

  pull_request:
    paths-ignore:
      - '*.md'
      - '*.txt'
      - '**/version.rb'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - head
          - 3.4
          - 3.3
          - 3.2

          - truffleruby
          - truffleruby-head

          - jruby
          - jruby-head

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version:  ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run specs with code coverage
        uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID:
        with:
          coverageCommand: bundle exec rake
        continue-on-error: ${{ matrix.allow-fail || false }}
        id: test

      - name: >-
          Test ${{ steps.test.outcome }}
        run: |
          ruby -v
